### ISSUE TITLE
前端手机代码无法部署

### ISSUE THREAD

**Issue by FangAzz-z** [qwdigital/LinkWechat#2]
您好，我在部署侧边栏的时候发现，一直报错。最后跟踪代码发现有发起一个企微登录的请求显示404，我在后台发现没有这个入口，是不是这块代码漏了？可以帮忙看看么
![bb24808b577af5a97df6b91314a1e29](https://user-images.githubusercontent.com/8545416/205550720-8da2763a-d086-4771-b5eb-993252b27fd4.png)
![9dc59f623ee67b52dc8393b4dcd13ae](https://user-images.githubusercontent.com/8545416/205550729-2f8376ee-c971-4280-aa6f-8f76219cb1e9.png)

**Comment by sxjangdongqin** [comment]
代码已更新！
