### ISSUE TITLE
微信企业号扫码登录之后，又跳回到登录页面

### ISSUE THREAD

**Issue by demonhuahua** [qwdigital/LinkWechat#3]
微信企业号扫码后挑战的url如下：
http://192.168.50.79/?code=code=W5HKpUnyEph7KlTk9-pDd435od7SGvjzFUQeQmI&appid=ww0357addddddfe#/login?redirect=%2F

微信企业号扫码登录之后，又跳到登录页面？
如下是我的wecomeLoginUrl的配置，请问哪里有问题吗？
wecomeLoginUrl: https://open.work.weixin.qq.com/wwopen/sso/qrConnect?appid=ww0357addddddfe&agentid=1000003&redirect_uri=http://192.168.50.79/#/authRedirect&state=web_login

**Comment by sxjangdongqin** [comment]
回掉没开源！
